### ISSUE TITLE
read: Tls::WantPollin

### ISSUE THREAD

**Issue by mattn** [Asmod4n/mruby-tls#3]
```
client = Tls::Client.new
client.connect('github.com:443').write("GET / HTTP/1.1\r\nHost: github.com\r\nConnection: close\r\n\r\n")
print client.read
client.close
```
This code getting error.

```
$ ./bin/mruby test.rb 
trace (most recent call last):
	[1] test.rb:3
test.rb:3:in read: Tls::WantPollin
```

Ubuntu 22.04 64bit.

**Comment by mattn** [comment]
Probably, socket may not be ready. So EAGAIN or EWOULDBLOCK is returned maybe.

**Comment by mattn** [comment]
```
client = Tls::Client.new
client.connect('github.com:443').write("GET / HTTP/1.1\r\nHost: github.com\r\nConnection: close\r\n\r\n")
while 1
  begin
    print client.read
    break
  rescue Tls::WantPollin
  end
end
client.close
```
Works. Is this your expected?

**Comment by Asmod4n** [comment]
Hmm, have to check upstream if something has changed.

**Comment by Asmod4n** [comment]
I won’t get near a dev pc till Saturday, but the want poll in and out exceptions should only be thrown in async mode.

**Comment by Asmod4n** [comment]
Looks like something changed, take a look at https://man.openbsd.org/tls_write.3 and their examples.

**Comment by Asmod4n** [comment]
@mattn 
I've rewritten how mruby-tls works, take a look at the examples.
for blocking IO the gem now handles everything automatically.
